source/includes/_identity.md

The example API calls were using the QA hostname

---

source/includes/_campaigns_overview_report.md

**References**: [ANALYTICS-1865](https://tickets.reachlocal.com/browse/ANALYTICS-1865)
The documentation for the [campaigns overview endpoint](https://reachlocal.github.io/api-docs/#campaigns-overview-report) says that it includes activity for the previous 30 days, but it doesn't mention how it limits campaigns and cycles to those that have had activity in the previous year.  Update the documentation to clearly explain this limitation.
This endpoint does accept a start_date parameter, but we don't want to encourage usage of this feature due to performance concerns so we are not publishing it.
Verify that the documentation changes are correct and don't contain any spelling or other grammar errors.

ANALYTICS-1865 Enhance campaigns overview documentation

---

source/includes/_capture_external_event_api.md

I feel it's inapropriate to provide a partener with API
documentation that potentially includes the name of a
competitor.

Remove NanoRep from CEEA documentation.

---

source/includes/_capture_discovery.md

Clarifies the default time zone that will be used for the Capture Discovery report.

Capture Discovery time zone clarity

---

source/includes/_creatives.md

**References**: [ANALYTICS-3052](https://jira.gannett.com/browse/ANALYTICS-3052)
Adds documentation for the Creatives API.

ANALYTICS-3052 | Add Creatives API Documentation

---

source/includes/_unified_display_campaign_metrics.md

Last table in unified-reporting documentation isn't displaying correctly.  This fixes that.

Fix Unified Reporting Table Formatting

---

source/includes/_lips_contact_interactions.md

*References*:  [ANALYTICS-3835](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/61)

ANALYTICS-3835 | LIPS: Provide total events and unread events by event_type

---

source/includes/_device_breakdowns.md

**Code Changes**: [ANALYTICS-3964](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1462)

ANALYTICS-3964 Display Device Breakdowns

---

source/includes/_campaigns_and_cycles.md

**References**: [ANALYTICS-4038](https://jira.gannett.com/browse/ANALYTICS-4038)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1516
As a user, I would like to find what GMAID a campaign (or -campaign) belongs to by searching with a text string.
```
curl -L -X GET 'http://localhost:3001/client_reports/campaigns?query=gci' \
-H 'Authorization: reachanalyticsreportingservicetoken'
```
The default platform_id is 1
```
curl -L -X GET 'http://localhost:3001/client_reports/campaigns?query=gci&platform_id=3' \
-H 'Authorization: reachanalyticsreportingservicetoken'
```
The default page is 1
```
curl -L -X GET 'http://localhost:3001/client_reports/campaigns?query=gci&page=1000' \
-H 'Authorization: …
```

ANALYTICS-4038 Campaign Name Search API

---

source/includes/_google_analytics.md

**References**: [ANALYTICS-4166](https://jira.gannett.com/browse/ANALYTICS-4166)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1548
Neighborly wants to see more results and the page title for 2 GA reports.

ANALYTICS-4166 | add-more-pages-to-ga-report

---

source/includes/_pub_sub_messages.md

**References**: [ANALYTICS-4175](https://jira.gannett.com/browse/ANALYTICS-4175)
**Code PR**: https://github.com/GannettDigital/identity_service/pull/349
Publish create, update and destroy messages for companies product model.

ANALYTICS-4175 Document Pub/Sub messages

---

source/includes/_lips_tags.md

**References**: [ANALYTICS-4219](https://jira.gannett.com/browse/ANALYTICS-4219)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/138
We needed to fix the tags post curl in lips tags docs

ANALYTICS-4219 | 500_response_when_tag_create

---

source/includes/_lips_contacts.md

**References**: [ANALYTICS-4245](https://jira.gannett.com/browse/ANALYTICS-4245)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/151
We needed to add 3 additional fields into the lips contacts get endpoints.

ANALYTICS-4245 | Include_additional_fields_into_LIPS

---

source/includes/_target_geofence.md
source/includes/_video_activity.md

**References**: [ANALYTICS-4227](https://jira.gannett.com/browse/ANALYTICS-4227)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1573
adding some unique_household data to target geofence and video activity

ANALYTICS-4227-add-unique_houshold-household_frequency

---

source/includes/_search_campaign_metrics.md

**References**: [ANALYTICS-4255](https://jira.gannett.com/browse/ANALYTICS-4255)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1583
Added top search metrics in the campaign totals.

ANALYTICS-4255 | include_totals_by_campaign_with_top_search_metrics

---

source/includes/_google_analytics.md
source/includes/_google_services.md
source/includes/_neighborly_location_review_details.md

**References**: [ANALYTICS-4338](https://jira.gannett.com/browse/ANALYTICS-4338)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1606
Updates to allow Neighborly to share GA credentials across each brand.

ANALYTICS-4338 | update-neighborly-ga-system

---

source/includes/_conversion_zone_geofences.md
source/includes/_target_geofence.md

**References**: [ANALYTICS-4312](https://jira.gannett.com/browse/ANALYTICS-4312)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1616
adding earliest date available to conversion zone and target geofence apis

ANALYTICS-4312 | target-geofence-earliest-date-available

---

source/includes/_lips_contact_interactions_totals.md

**References**: [ANALYTICS-4305](https://jira.gannett.com/browse/ANALYTICS-4305)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/169
This is the new API for the events totals.

ANALYTICS-4305 | extract_event_totals_and_optimize_old_query

---

source/includes/_target_geofence.md
source/includes/_target_geofence_totals.md

**References**: [ANALYTICS-4377](https://jira.gannett.com/browse/ANALYTICS-4377)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1628
target_geofence is not performing super great so we are moving the totals to their own API

ANALYTICS-4377 | target-geofence-totals

---

source/includes/_marketing_activity.md

**References**: [ANALYTICS-4402](https://jira.gannett.com/browse/ANALYTICS-4402)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1649
Confirm with Josh, but this should be good to remove from Marketing Activity API now that the front-end in Client Center supports it.

ANALYTICS-4402 | Remove second date ranges on Marketing Activity API

---

source/includes/_lips_contact_interactions.md
source/includes/_lips_contacts.md

**References**: [ANALYTICS-4457](https://jira.gannett.com/browse/ANALYTICS-4457)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/191
Added docs for lead archiving/unarchiving

ANALYTICS-4457 | Added docs for lead archiving/unarchiving

---

source/includes/_contact_interactions.md

**References**: [ANALYTICS-4498](https://jira.gannett.com/browse/ANALYTICS-4498)
**Code PR**: none
A customer pointed out a documentation issue.  This is the correction.

ANALYTICS-4498 extra_fields type documentation

---

source/includes/rars_unique_domain.md

**References**: [ANALYTICS-4524](https://jira.gannett.com/browse/ANALYTICS-4524)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1722
migrating capture-reporting endpoint to RARS.

ANALYTICS-4524 | migrate-unique-domains

---

source/includes/_wpc.md

**References**: [ANALYTICS-4681](https://jira.gannett.com/browse/ANALYTICS-4681)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1763
**Regression PR**: https://github.com/GannettDigital/reporting_service_qa_automation/pull/327
In the WPC api add a parameter to allow api client to turn intervals on or off.  This was done by adding support for an interval_size of none.

ANALYTICS-4681 Support interval_size of none

---

source/includes/_google_analytics_data.md
source/includes/_google_analytics_data_pages.md

**References**: [ANALYTICS-4730](https://jira.gannett.com/browse/ANALYTICS-4730)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1770
this filter doesn't work in ga4 so we are removing it.

ANALYTICS-4730 | remove-page-path

---

source/includes/_marketing_activity.md
source/includes/_unique_domains.md

**References**: [ANALYTICS-4768](https://jira.gannett.com/browse/ANALYTICS-4768)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1774
In the Marketing Activity api add another item of bookings count in the results.
Like
```
"direct": {
"intervals": [
{
"start_date": "2023-01-26",
"bookings": 7,
"visits": 7,
"chats": 0,
"calls": 0,
"forms": 0
}
],
"totals": {
"total_bookings": 7,
"total_visits": 7,
"total_calls": 0,
"total_chats": 0,
"total_forms": 0
}
},
```
The following advertisers have at least 5 booking events since the start of the year: USA_421655, USA_362699, USA_414384, USA_414365, USA_382461, USA_430601, USA_417899, USA_413778, USA_408371, USA_425384, USA_414303.  USA_417899 seems the best
```
curl …
```

ANALYTICS-4768 Add booking counts

---

source/includes/_unique_domains.md

**References**: [ANALYTICS-4780](https://jira.gannett.com/browse/ANALYTICS-4780)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1773
[In capture reporting we have](https://confluence.gannett.com/display/LIQAP/Unique+Domains)
```
/unique-domains/[query_params]
```
and [in RARS we have](https://github.com/GannettDigital/api-docs/blob/master/source/includes/rars_unique_domain.md)
```
/unique_domain/[gmaid]
```
This should be plural, it returns domains.   RARS routes use underscores and this is now a RARS API.  While we could support the hyphen in the route, we also require a different parameter scheme so this change is acceptable for consistency.
```
curl -L …
```

ANALYTICS-4780 Rename unique domains route

---

source/includes/_socialads_campaign_metrics.md

**References**: [ANALYTICS-4774](https://jira.gannett.com/browse/ANALYTICS-4774)
**Code PR**:  https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1778
Facebook purchase metrics are now being retrieved in Platform.  Need to add metric definitions to include these in our reporting APIs for facebook.
 Add the following metrics to the Facebook Breakdowns (DailySocialDemographicActivity) model
| Name | Field value in Platform | Field in API response |
| --- | --- |--- |
| Purchases | actions.omni_purchase | omni_purchase_actions |
| Purchase ROAS | purchase_roas.omni_purchase | omni_purchase_action_values |
| Purchase Conversion Value | action_values.omni_purchase | omni_purchase_purchase_roas |
There is a manual migration for …

ANALYTICS-4774 Add Facebook Purchase conversion metrics

---

source/includes/_google_analytics_data_pages.md

**References**: [ANALYTICS-4820](https://jira.gannett.com/browse/ANALYTICS-4820)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1793
A new ga4 report. It replaces an older report that is no longer needed.

ANALYTICS-4820 | new-ga4-report

---

source/includes/_email.md
source/includes/_email_old.md

**References**: [ANALYTICS-4807](https://jira.gannett.com/browse/ANALYTICS-4807)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1794
Support the scenario where a single MCID might have more than one Site Impact campaign associated it with it.
Create a new version of the API so that Client Center can continue to use the original endpoint.

ANALYTICS-4807 Email API V2

---

source/includes/_xmedia_channel.md

**References**: [ANALYTICS-4824](https://jira.gannett.com/browse/ANALYTICS-4824)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1791
XMO is adding LSA as part of their bundle offerings and need these campaigns visible in Client Center reporting. Update the **xmo_channels** API to include these campaigns in the channel breakout sections under **cycles** and **totals_by_channel**.

ANALYTICS-4824 Added support for LSA channel

---

source/includes/_gustav_daily_creative_metrics.md

**References**: [EDGE-8296](https://jira.gannett.com/browse/EDGE-8296)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1811
Added a global_master_campaign_id[] filter to Gustav Daily Creative Metrics.

added global_master_campaign_id[] to Gustav Daily Creative Metrics

---

source/includes/_lips_contact_interactions.md
source/includes/_lips_contact_interactions_totals.md

**References**: [EDGE-9045](https://jira.gannett.com/browse/EDGE-9045)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/289
We need to add a dyipost, facebook and promotion as sub types in lips.

EDGE-9045 | data_subtyping_in_lips

---

source/includes/_lips_contact_interactions.md

**References**: [EDGE-8303](https://jira.gannett.com/browse/EDGE-8303)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/291
The **target_phone** field is part of the Call Event data provided by Capture. In instances where a client has phone replacement tracking provisioned in Capture the target_phone value is the phone number that was displayed on the  client website (final number called in a phone replacement flow).
In the contact interactions API include the field of target_phone in the Call event response data.
A call to the Contact Interactions API with a GMAID that has Call Events tracked (phone replacement provisioned) will include the **target_phone** field and value in the Call events data as part of the response data. …

EDGE-8303 Add target_phone

---

source/includes/_xmedia.md.erb
source/includes/_xmedia_channel.md.erb

**References**: [EDGE-9348](https://jira.gannett.com/browse/EDGE-9348)
**Code PR**:
[9348](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1893)
Reflects additions of the `views` metric which is the `clicks` metric when the `publisher_id = 65`, otherwise 0. 
Also adds a new `video` channel for the `xmedia_channels` API call, introducing a new `video` node.

EDGE-9348 xmedcia channels view video channel
