GannettDigital/api-docs

source/includes/_keyword_compliance_report.md, source/includes/_search_compliance_report.md, source/includes/_youtube.md, source/index.html.md
Add Google Search, Google Keyword reports, and Youtube device breakdowns.
=> 1456 update public api docs

source/includes/_capture_external_event_api.md
Authentication will handled upstream. Also, modified description of chatTextFull to mention transcript.
=> Removed Authentication from Capture External Event

source/includes/_advertiser_contact_info.md, source/includes/_authentication.md, source/includes/_campaigns_overview_report.md, source/includes/_campaigns_totals.md, source/includes/_capture_external_event_api.md, source/includes/_display_activity_report.md, source/includes/_facebook_campaign_report.md, source/includes/_identity.md, source/includes/_keyword.md, source/includes/_keyword_compliance_report.md, source/includes/_lead_detail.md, source/includes/_search_activity_report.md, source/includes/_search_compliance_report.md, source/includes/_total_track.md, source/includes/_youtube.md, source/index.html.md
**References**: [ANALYTICS-1512](https://tickets.reachlocal.com/browse/ANALYTICS-1512)
Update the authentication to reflect the change made for [ANALYTICS-1492](https://tickets.reachlocal.com/browse/ANALYTICS-1492) (We only want to publish support for Bearer tokens). 
Add public facing documentation for the API added in [ANALYTICS-1437](https://tickets.reachlocal.com/browse/ANALYTICS-1437).
To test locally, follow the instructions in the README for this project to run locally.
=> ANALYTICS-1512 Add documentation for identity endpoint

source/includes/_facebook_campaign_report.md
https://tickets.reachlocal.com/browse/ANALYTICS-1545
=> Add leads to facebook report

source/includes/_display_activity_report.md
**References**: [ANALYTICS-1438](https://tickets.reachlocal.com/browse/ANALYTICS-1438)
Adds walk_ins and CPW to the Display Activity Report Documentation
=> Add Walk-Ins and CPW to Display

source/includes/_call_connect.md, source/index.html.md
This endpoint does not actually exist at the moment. The response
payload for a 400 Bad Request has not been determined yet.
=> Add doc for Call Connect endpoint

source/includes/_geofence_summary_report.md, source/index.html.md
https://tickets.reachlocal.com/browse/ANALYTICS-1603
=> Add GeoFence Summary Report Documentation

source/includes/_geofence_summary_report.md
https://tickets.reachlocal.com/browse/ANALYTICS-1657
=> Add Campaign-Level Totals for GeoFence

source/includes/_display_creative_report.md, source/index.html.md
https://tickets.reachlocal.com/browse/ANALYTICS-1671
=> Add Display Creative Report Documentation

source/includes/_campaigns_totals.md, source/includes/_display_activity_report.md, source/includes/_facebook_campaign_report.md, source/includes/_keyword.md, source/includes/_keyword_compliance_report.md, source/includes/_lead_detail.md, source/includes/_search_activity_report.md, source/includes/_search_compliance_report.md, source/includes/_total_track.md, source/index.html.md, source/javascripts/lib/_energize.js
Some removal and changes to order of information. Changes to spacing and capitalization in comments.
=> Documentation changes

source/includes/_keyword.md
Adds documentation update to include the new types[] param in the Keyword Report and the new `type` attribute for each keyword.
=> ANALYTICS-2136 | Update Keyword Report for Display

source/includes/_display_activity_report.md, source/includes/_display_creative_report.md, source/includes/_unified_display_report.md, source/index.html.md
This has been added as specified in the unified_display.md doc and in collaboration with Jayanthi.
=> Added Unified Display Markdown

source/includes/_chat_summary.md, source/includes/_cvt_events.md, source/index.html.md
Added information for Chat Summary API and adjusted CVT/Web Events API.
=> Expose Chat Summary and Adjust CVT Documentation

source/includes/_campaigns.md, source/includes/_new_2020.md, source/includes/_unified_display_report.md, source/index.html.md
Added "New/Updated: 2020" section and made small text changes to Campaigns
=> Minor format/text changes.

source/includes/_campaigns.md, source/includes/_campaigns_overview_report.md, source/index.html.md
Updated response and added response data details; moved Campaigns under New/Updated section.
=> Minor updates

source/includes/_api_overview.md, source/includes/_chat_summary.md, source/includes/_lead_detail.md, source/includes/_lsa_campaigns.md, source/index.html.md
No Ticket.  This is leftover from the bid rewrite.
=> Update LSA Campaigns Report

source/includes/_age_gender.md
=> ANALYTICS-3166 Updates for age and gender report

source/includes/_premium_listing_manage_profile.md
**References**: [ANALYTICS-3157](https://jira.gannett.com/browse/ANALYTICS-3157)
[Identity service API](https://github.com/reachlocal/identity_service/pull/249)
Create API endpoints on identity service to manage an Uberall user profile
=> ANALYTICS-3157 Manage Premium listing user profile

source/includes/_addressable_geofence.md, source/includes/_call_connect.md, source/includes/_campaigns_overview_report.md, source/includes/_capture_external_event_api.md, source/includes/_cogs_api.md, source/includes/_contact_interactions.md, source/includes/_contacts.md, source/includes/_creatives.md, source/includes/_crm_webhooks.md, source/includes/_display_campaign_metrics.md, source/includes/_email.md, source/includes/_google_keyword_report.md, source/includes/_keyword_performance_metrics.md, source/includes/_search_campaign_metrics.md, source/includes/_unified_display_campaign_metrics.md, source/includes/lead_event_feed_service/call_events/_index.md, source/includes/lead_event_feed_service/chat_events/_index.md, source/includes/lead_event_feed_service/leads/_index.md, source/includes/lead_event_feed_service/web_events/_index.md
aligned docs requests and response
=> ANALYTICS-3137 Align parameter and response objects

source/includes/_campaigns_overview_report.md
[The corresponding code changes are in this PR](https://github.com/reachlocal/reach-analytics-reporting-service/pull/1324)
=> ANALYTICS-33485 | Campaign Overview - Add Qualified Web Events

source/includes/_identity_users.md
Related pull request: [ANALYTICS-3513](https://github.com/GannettDigital/identity_service/pull/274)
Realated ticket: [ANALYTICS-3513](https://jira.gannett.com/browse/ANALYTICS-3513)
=> ANALYTICS-3513 | Identity - Create User model and CRUD

source/includes/_unified_display_campaign_metrics.md
RARS pull request: 
https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1350
=> ANALYTICS-3256 | Unified Display API update: Include full channel

source/includes/_crm_webhooks.md
As an user of the CRM integration solutions I want to see an example of the data the webhook  and Zapier will provide.
Requirements
update webhook payload info & update example 
https://github.com/GannettDigital/api-docs/blob/master/source/includes/_crm_webhooks.md
https://github.com/GannettDigital/api-docs/blob/master/source/includes/_zapier_contact_interactions.md
Published here
https://doc.api.localiq.com/#lead-info-apis-webhooks-crm-webhooks-webhook-payload
https://doc.api.localiq.com/#lead-info-apis-webhooks-localiq-app-on-zapier-contact-interactions
Has this changed too ?
https://github.com/GannettDigital/api-docs/blob/master/source/includes/_contact_interactions.md
=> ANALYTICS-3597 | Webhook/Zapier payload documentation update

source/includes/_etl_reports.md, source/includes/etl_reports/_etl_lead_attribution.md
Docs for ETL Lead Attribution Report.  This is not a public API.
=> ANALYTICS_3459 | ETL Lead Attribution Report

source/includes/_gustav_daily_creative_metrics.md
**References**: [ANALYTICS-3619](https://jira.gannett.com/browse/ANALYTICS-3619)
[Code change PR](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1373)
=> ANALYTICS-3619 Gustav Daily Creative Metrics API

docker-compose.yml
While on-boarding I discovered that dockerfiles now require `services:` key. 
from project root run`docker-compose up` in terminal and expect to see project build/run successfully
=> ANALYTICS-3698 | Updating Dockerfile

source/includes/etl_reports/_etl_lead_attribution.md
Companion PR: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1397
=> ANALYTICS-3689 - update etl_lead_attribution_report

source/includes/_lips_contacts.md, source/includes/_lips_events.md
For https://github.com/GannettDigital/lead-ingestion-publication-service/pull/22
=> ANALYTICS-3631 | Document LIPS Events API

source/includes/_identity_users.md
**References**: [pull request](https://github.com/GannettDigital/identity_service/pull/287)
=> ANALYTICS-3691 | Freemium: Modify User record to store LDAP info

Gemfile.lock, source/includes/_lips_contact_interactions.md
reference:  [ANALYTICS-3724](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/43)
=> ANALYTICS-3724 | lips contact interaction api

source/includes/_google_site_urls.md
[Code PR-1413](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1413)
=> ANALYTICS-3775 | add google site urls endpoint

source/includes/_lips_contact_interactions.md
**Reference**: [ANALYTICS-3781](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/50)
=> ANALYTICS-3781 | LIPS: UPDATE endpoint for ContactInteractions

source/includes/_marketing_activity.md
**Refference**: [ANALYTICS-3733](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1420)
=> ANALYTICS-3733 | A Better Discovery API (in RARS)

source/includes/_lips_contact_interactions.md
Reference: [ANALYTICS-3822](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/60)
=> ANALYTICS-3822 | Add channel to Contact interactions API

source/includes/_lips_contact_interactions.md
**References**: [ANALYTICS-3862](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/62)
=> ANALYTICS-3862 | Continue cleanup of EventsController

source/includes/_lips_contact_interactions.md, source/includes/_marketing_activity.md
**Reference**: [ANALYTICS-3857](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/65)
=> ANALYTICS-3857 | Update contact interaction api

source/includes/_marketing_activity.md
**Pull Requests**:  [ANALYTICS-3919](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1439)
=> ANALYTICS-3919 | Updates to Marketing Activity API 

source/includes/_campaigns_and_cycles.md, source/includes/_campaigns_overview_report.md
**Code PR**:  [ANALYTICS-3859](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1442)
=> ANALYTICS-3859 | add off platform campaign activity

source/includes/_identity_advertisers.md
**Identity service**: [ANALYTICS-3954](https://github.com/GannettDigital/identity_service/pull/319)
=> ANALYTICS-3954 | Remove support for match_params

source/includes/_identity_companies.md
This is a valid working route and is described lower in the documentation.
=> add missing companies/login_user route from route table

source/includes/_identity_companies.md, source/includes/_identity_login_users.md
Correct the POST api to not nest in a `company` object.  
Correct the PUT api to not allow `login_user_id`.
=> EDGE-7019 | Update Companies API

source/includes/_lips_contact_interactions.md
Code PR: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/84
=> ANALYTICS-3862 | add event_type filter

source/includes/_identity_login_users.md
Code PR: https://github.com/GannettDigital/identity_service/pull/326
=> [ANALYTICS-3983] - Update docs

source/includes/_campaigns_and_cycles.md
**References**: [ANALYTICS-3970](https://jira.gannett.com/browse/ANALYTICS-3970)
**Source Code Changes**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1481
=> ANALYTICS-3970 Video Activity

source/includes/_video_activity.md
Source PR: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1489
=> ANALYTICS-3996 Video Activity API

source/includes/_identity_companies.md
**References**: [ANALYTICS-4018](https://github.com/GannettDigital/identity_service/pull/332)
=> ANALYTICS-4018 | Add sic_code to Identity Company endpoint

source/includes/_socialads_ad_set_metrics.md
**References**: [ANALYTICS-4043](https://jira.gannett.com/browse/ANALYTICS-4043)
**Code PR**: [1496](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1496)
=> ANALYTICS-4043 | add-full-channel-to-ad-set-report

source/includes/_brand_awareness.md
**References**: [ANALYTICS-4036](https://jira.gannett.com/browse/ANALYTICS-4036)
[Code PR](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1509)
=> ANALYTICS-4036 Add chat to brand_awareness

source/includes/_lips_contacts.md
**Ref**: [4103 ](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/112)
=> ANALYTICS-4103 | LIPS: Update Contacts in preparation for program automation

source/includes/_lips_contacts.md
[Code PR](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/112)
=> ANALYTICS-4105 Contact Create/update/Delete

source/includes/_addressable_geofence.md
**Ref**: [ANALYTICS-4100](https://jira.gannett.com/browse/ANALYTICS-4100)
=> ANALYTICS-4100 | ReachLocal Addressable GeoFence Reporting

source/includes/_contact_interactions.md
**Ref**: [ANALYTICS-4170](https://github.com/GannettDigital/lead-ingestion-publication-service/pull/128)
=> ANALYTICS-4170 | Endpoint for retrieving a contract interaction by ID

.github/PULL_REQUEST_TEMPLATE.md, source/includes/_geofence_campaign_metrics.md
**References**: [ANALYTICS-4068](https://jira.gannett.com/browse/ANALYTICS-4068)
Code PR: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1541
=> ANALYTICS-4068 Add date range validation

source/includes/_contact_interactions.md, source/includes/_lips_contact_interactions.md
**References**: https://github.com/GannettDigital/api-docs/pull/249
We put these docs in the wrong file. The file they are currently in is public facing so we need should move them ASAP.
=> move docs to correct file

source/includes/_google_analytics.md
**References**: [ANALYTICS-4168](https://jira.gannett.com/browse/ANALYTICS-4168)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1551
New report and second_data_sets
=> ANALYTICS-4168 | new-report-new-param-ga-report

source/includes/_lips_contact_interactions.md, source/includes/_lips_contacts.md
**References**: [ANALYTICS-4183](https://jira.gannett.com/browse/ANALYTICS-4183)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/132
Adding a couple of data points to the contact interactions endpoint
=> Analytics-4183 | add page url and preferred contact method

source/includes/_lips_contact_interactions.md, source/includes/_lips_tags.md
**References**: [ANALYTICS-4112](https://jira.gannett.com/browse/ANALYTICS-4112)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/130
Added docs for the tags maintanence in lips
=> ANALYTICS-4112 | Lips_tags_maintenence_API

source/includes/_pub_sub_messages.md
**References**: [ANALYTICS-4109](https://jira.gannett.com/browse/ANALYTICS-4109)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/126
=> ANALYTICS-4109 | LIPS: Pubsub of certain events

source/includes/_addressable_geofence.md, source/includes/_conversion_zone_geofences.md
**References**: [ANALYTICS-4174](https://jira.gannett.com/browse/ANALYTICS-4174)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1555
=> ANALYTICS-4174 | Conversion-Fences-Report

source/includes/_brand_awareness.md
**Ref**: [ANALYTICS-4149](https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1540)
=> ANALYTICS-4149 | Brand Awareness: Remove Geofence as a breakdown

source/includes/_workflow_builder.md
**References**: [ANALYTICS-4204 ](https://jira.gannett.com/browse/ANALYTICS-4204 )
**Code PR**: https://github.com/GannettDigital/
=> ANALYTICS-4204 | Documentation for workflow builder

source/includes/_lips_contacts.md
**CODE-PR**: (https://github.com/GannettDigital/lead-ingestion-publication-service/pull/139)
=> ANALYTICS-4104-enhance-contacts-search

source/includes/_google_analytics.md
**References**: [ANALYTICS-4231](https://jira.gannett.com/browse/ANALYTICS-4231)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1564
Adding a new metric and changing date range
=> ANALYTICS-4231 | update-GA-report

source/includes/_lips_contacts.md
**References**: [ANALYTICS-4262](https://jira.gannett.com/browse/ANALYTICS-4262)
**Code PR**: github.com/GannettDigital/lead-ingestion-publication-service/pull/153
=> ANALYTICS-4262 | more contact filters

source/includes/_neighborly_location_review_details.md
**References**: [ANALYTICS-4271 ](https://jira.gannett.com/browse/ANALYTICS-4271 )
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1580
=> ANALYTICS-4271 | Endpoint to add Neighborly Web Location ID

source/includes/_google_analytics_data.md
**References**: [ANALYTICS-4184](https://jira.gannett.com/browse/ANALYTICS-4184)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1565
The docs for google analytics 4 report, which will replace the google universal report.
=> ANALYTICS-4184 | RARS_create_GA4_report

source/includes/_contacts.md, source/includes/_lips_contact_interactions.md, source/includes/_lips_contacts.md, source/includes/_lips_events.md
**References**: [ANALYTICS-4288](https://jira.gannett.com/browse/ANALYTICS-4288)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/161
=> ANALYTICS-4288 | LIPS: Increase pagination limits for trusted callers

source/includes/_lips_contacts.md
**References**: [ANALYTICS-4256](https://jira.gannett.com/browse/ANALYTICS-4256)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/158
update contact status to have limited choices.
=> ANALYTICS-4256 | contacts-status-update

source/includes/_google_keyword_report.md, source/includes/_keyword_performance_metrics.md
**References**: [ANALYTICS-4253](https://jira.gannett.com/browse/ANALYTICS-4253)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1601
=> ANALYTICS-4253 | Search & keyword metrics not matching

source/includes/_etl_reports.md
**References**: [ANALYTICS-0000](https://jira.gannett.com/browse/ANALYTICS-4352)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1624
=> ANALYTICS-4352 | Add pagination to ETL index

source/includes/_lips_contacts.md
**References**: [ANALYTICS-4385](https://jira.gannett.com/browse/ANALYTICS-4385)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/179
=> ANALYTICS-4385 | Verify that "Company" exists on Contact Record and is exposed in API response

source/includes/_marketing_activity.md
**References**: [ANALYTICS-4299](https://jira.gannett.com/browse/ANALYTICS-4299)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1604
=> ANALYTICS-4299 | Marketing Activity API: Support new referrer types

source/includes/_lips_contact_interactions.md, source/includes/_lips_contacts.md, source/includes/_lips_events.md
**References**: [ANALYTICS-4339](https://jira.gannett.com/browse/ANALYTICS-4339)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/183
Added notes to contacts and events
=> ANALYTICS-4339 | LIPS: Contact and lead notes

source/includes/_brand_awareness.md
**References**: [ANALYTICS-4396](https://jira.gannett.com/browse/ANALYTICS-4396)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1641
=> ANALYTICS-4396 Low-Value Web Events being shown as leads

source/includes/_campaigns_and_cycles.md
The current attempt to hid these docs is not working. You can see them but this feature doesn't work for external callers.
=> hide-campaigns-search

source/includes/_campaigns_and_cycles.md
**References**: [ANALYTICS-4468](https://jira.gannett.com/browse/ANALYTICS-4468)
**Code PR**: none
```
curl -L -X GET 'https://data-connect-prod.gannettdigital.com/client_reports/campaigns/USA_258209?report_type=wpc' \
-H 'Authorization: TRUSTED_TOKEN'
```
works, so the documentation just needed updating.
=> ANALYTICS-4468 wpc is a recognized campaign report type

source/includes/_lips_contact_interactions.md, source/includes/_lips_contact_interactions_totals.md, source/includes/_lips_lsa_leads.md
**References**: [ANALYTICS-4405](https://jira.gannett.com/browse/ANALYTICS-4405)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/199
=> ANALYTICS-4405 | Store the booking info in LIPS

source/includes/_lips_booking_events.md, source/includes/_lips_contact_interactions.md, source/includes/_lips_events.md
**References**: [ANALYTICS-4490](https://jira.gannett.com/browse/ANALYTICS-4490)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/200/files
We need to add details for Booking events
=> ANALYTICS-4490 | bookings_lead_type_added_to_lips_endpoint

source/includes/_conversion_zone_geofence.md
**References**: [ANALYTICS-4465](https://jira.gannett.com/browse/ANALYTICS-4465)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1671
=> ANALYTICS-4465 | Conversion Zone zip code import & filtering

source/includes/_target_geofence.md
**References**: [ANALYTICS-4466](https://jira.gannett.com/browse/ANALYTICS-4466)
**Code PR**:https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1676
=> ANALYTICS-4466 | Target Geofence zip code filtering

source/includes/_zip_codes.md
**References**: [ANALYTICS-4467](https://jira.gannett.com/browse/ANALYTICS-4467)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1673
We need to add a zip codes api based on the new zip codes geofences table.
=> ANALYTICS-4467 | available_zip_codes_api

source/includes/_wpc.md
**References**: [ANALYTICS-4483](https://jira.gannett.com/browse/ANALYTICS-4483)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1683
=> ANALYTICS-4483 | WPC API - more columns!

source/includes/_authentication.md, source/includes/_google_search_console.md, source/includes/_google_services.md, source/includes/_google_site_urls.md, source/includes/_identity_advertisers.md, source/includes/_identity_companies.md, source/includes/_identity_login_users.md, source/includes/_identity_products.md, source/includes/_lips_contact_interactions.md, source/includes/_lips_contact_interactions_totals.md, source/includes/_lips_contacts.md, source/includes/_lips_events.md, source/includes/_lips_fpd_events.md, source/includes/_lips_tags.md, source/includes/_premium_listings_business.md, source/includes/_premium_listings_business_insights.md, source/includes/_premium_listings_business_locations.md, source/includes/_premium_listings_business_review_insights.md, source/includes/_premium_listings_location.md, source/includes/_premium_listings_location_insights.md, source/includes/_premium_listings_location_review_details.md, source/includes/_premium_listings_location_reviews.md
**References**: [ANALYTICS-4528](https://jira.gannett.com/browse/ANALYTICS-4528)
**Code PR**: https://github.com/GannettDigital/
=> ANALYTICS-4528 | LIPS: Clean up LIPS API documentation removing x-api-key from curl examples

source/includes/_target_geofence_totals.md
**References**: [ANALYTICS-4516](https://jira.gannett.com/browse/ANALYTICS-4516)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1693
=> ANALYTICS-4516 | target_geofences_totals

source/includes/lead_paths.md
**References**: [ANALYTICS-4379](https://jira.gannett.com/browse/ANALYTICS-4379)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1689
We need to migrate the lead paths api from capture into rars
=> ANALYTICS-4379 | create_new_lead_paths_api

source/includes/_lips_contact_interactions_totals.md
**References**: [ANALYTICS-0000](https://jira.gannett.com/browse/ANALYTICS-0000)
**Code PR**: https://github.com/GannettDigital/
=> Lips totals

source/includes/_rars_top_referrers.md
**References**: [ANALYTICS-4522](https://jira.gannett.com/browse/ANALYTICS-4522)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1706
=> ANALYTICS-4522 | RARS: Migrate top_referrers endpoint to RARS

source/includes/_google_analytics.md, source/includes/_google_analytics_pages.md, source/includes/_neighborly_location_review_details.md
**References**: [ANALYTICS-4633](https://jira.gannett.com/browse/ANALYTICS-4633)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1733
=> ANALYTICS-4633 | add-segment

source/includes/_premium_listings_location.md, source/includes/_premium_listings_location_insights.md, source/includes/_premium_listings_location_review_details.md, source/includes/_premium_listings_location_reviews.md
**References**: [ANALYTICS-4538](https://jira.gannett.com/browse/ANALYTICS-4538)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1702
=> ANALYTICS-4538 | Premium Listings APIs for Australia GMAIDs

source/includes/_lips_site_status.md, source/includes/_site_status.md
**References**: [ANALYTICS-4523](https://jira.gannett.com/browse/ANALYTICS-4523)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/229
We need to migrate the site status api from capture.
=> ANALYTICS-4523_migrate_site_status_endpoint

source/includes/_lips_contact_interactions.md
**References**: [ANALYTICS-4653](https://jira.gannett.com/browse/ANALYTICS-4653)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/240
**Regression PR**: https://github.com/GannettDigital/reporting_service_qa_automation/pull/316
=> ANALYTICS-4653 Call events have malformed response

source/includes/_wpc.md
**References**: [ANALYTICS-4630](https://jira.gannett.com/browse/ANALYTICS-4630)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1751
this is a functional param that we left off the docs.
=> ANALYTICS-4630 | adding channel param

source/includes/_contact_interactions.md, source/includes/_edge_webhook.md
**References**: [ANALYTICS-4695](https://jira.gannett.com/browse/ANALYTICS-4695)
**Code PR**: None
The frequency with which our users create webhooks and expect them to be compatible with external services is alarming. Either our documentation is not clear and we are misleading our users, or they aren't reading our documentation. We have little control over user their behavior, but we can improve the documentation.
=> ANALYTICS-4695 Add warning

source/includes/_google_analytics_data.md, source/includes/_google_analytics_data_pages.md
**References**: [ANALYTICS-4662](https://jira.gannett.com/browse/ANALYTICS-4662)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1760
Added new GA4 metrics and added new report
=> ANALYTICS-4662 | ga4-updates

source/includes/_lips_contact_interactions.md
**References**: [ANALYTICS-4697](https://jira.gannett.com/browse/ANALYTICS-4697)
**Code PR**:https://github.com/GannettDigital/lead-ingestion-publication-service/pull/248
Added referring_url to chat and fixed other mistakes in docs.
=> ANALYTICS-4697 | new-field-chat-events

source/includes/_authentication.md, source/includes/_release_notes_2021.md, source/index.html.md
**References**: [ANALYTICS-4767](https://jira.gannett.com/browse/ANALYTICS-4767)
We are out of the direct support game 🎉
=> ANALYTICS-4767 | remove-email

source/includes/_age_gender.md, source/includes/_campaigns_and_cycles.md, source/includes/_campaigns_overview_report.md, source/includes/_creative_ad_metrics.md, source/includes/_cvt_events.md, source/includes/_display_campaign_metrics.md, source/includes/_gustav_daily_creative_metrics.md, source/includes/_socialads_ad_set_metrics.md, source/includes/_total_track.md, source/includes/_unified_display_campaign_metrics.md, source/includes/_web_events_metrics.md, source/includes/_wpc.md, source/includes/_xmedia.md, source/includes/_xmedia_channel.md
**References**: [ANALYTICS-4827](https://jira.gannett.com/browse/ANALYTICS-4827)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1795
=> Analytics 4827 | wpc shopping metrics

source/includes/_age_gender.md, source/includes/_campaigns_and_cycles.md, source/includes/_campaigns_overview_report.md, source/includes/_creative_ad_metrics.md, source/includes/_cvt_events.md, source/includes/_display_campaign_metrics.md, source/includes/_gustav_daily_creative_metrics.md, source/includes/_socialads_ad_set_metrics.md, source/includes/_total_track.md, source/includes/_unified_display_campaign_metrics.md, source/includes/_web_events_metrics.md, source/includes/_wpc.md, source/includes/_xmedia.md, source/includes/_xmedia_channel.md
**References**: [ANALYTICS-4819](https://jira.gannett.com/browse/ANALYTICS-4819)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1792
=> ANALYTICS-4819-shopping-campaign-type

source/includes/_contact_interactions.md
**References**: [EDGE-8325](https://jira.gannett.com/browse/EDGE-8325)
**Code PR**: https://github.com/GannettDigital/reachconvert/pull/2401
Adds call target to the contact interaction call node
=> EDGE-8325 - update call node for call interactions

source/includes/_shopping.md
**References**: [ANALYTICS-4818](https://jira.gannett.com/browse/ANALYTICS-4818)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1806
See code PR
=> ANALYTICS-4818 Shopping Metrics API

source/includes/_contact_interactions.md
**References**: [EDGE-8340](https://jira.gannett.com/browse/EDGE-8340)
**Code PR**: https://github.com/GannettDigital/reachconvert/pull/2403
Adds caller number and dialed number to CC contact interactions API
=> Adds caller_number and dialed_number to CC contact interactions API

source/includes/_gustav_daily_creative_metrics.md
**References**: [EDGE-8326](https://jira.gannett.com/browse/EDGE-8326)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1812
Added replay columns to the gustav_daily_creative_metrics API response.
=> added replay related cols to gustav_daily_creative_metrics

source/includes/_wpc.md
**References**: [EDGE-8576](https://jira.gannett.com/browse/EDGE-8576)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1831
Adding the CPM value to the _wpc documentation
=> EDGE-8576 | added the CPM value in the _wpc doc

source/includes/_identity_companies.md, source/includes/_identity_login_users.md
**References**: [EDGE-8670](https://jira.gannett.com/browse/EDGE-8670)
**Code PR**: https://github.com/GannettDigital/identity_service/pull/389
Added is_sales and google_place_id to companies.
=> added is_sales and google_place_id to companies

source/includes/_external_entities.md, source/includes/_lips_contact_interactions.md, source/index.html.md
**References**: [EDGE-8334](https://jira.gannett.com/browse/EDGE-8334)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/264
Documents new external entities API.
=> documented external entities API

source/includes/_google_services.md
**References**: [EDGE-8908](https://jira.gannett.com/browse/EDGE-8908)
**Code PR**: https://github.com/GannettDigital/api-docs
Updates to docs to reflect the changes in ticket 8908.
=> EDGE-8908 google_services api docs updates

source/includes/_gannett_display_report.md
**References**: [EDGE-9047](https://jira.gannett.com/browse/EDGE-9047)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1865
We need to remove moat metrics from RARS
=> EDGE-9047 | remove_moat

source/includes/_campaign_optimization.md
**References**: [EDGE-9181](https://jira.gannett.com/browse/EDGE-9181)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1878
Campaign optimization api docs
=> EDGE-9181 | campaign_optimization_api

source/includes/_lips_contact_interactions.md
**References**: [NXT-61](https://jira.gannett.com/browse/NXT-61)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/299
see code PR
=> NXT-61 Add support for SMSRequest form sub-type

source/includes/_marketing_activity.md.erb
**References**: [NXT-46](https://jira.gannett.com/browse/NXT-46)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1895
See code PR
=> NXT-46 Update Marketing Activity API to include SMSRequests

source/includes/_google_keyword_report.md
**References**: [EDGE-9405](https://jira.gannett.com/browse/EDGE-9405)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1904
**Regression PR**: https://github.com/GannettDigital/reporting_service_qa_automation/pull/377
=> EDGE-9405 Add CTR

source/includes/_lips_contact_interactions.md
**References**: [NXT-64](https://jira.gannett.com/browse/NXT-64)
**Code PR**: https://github.com/GannettDigital/lead-ingestion-publication-service/pull/303
=> NXT-64 Remove contacts

source/includes/_yelp_ad_metrics.md
**References**: [EDGE-9732](https://jira.gannett.com/browse/EDGE-9732)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1938
The Docs for Yelp Metrics API
=> EDGE-9732 | yelp_api

source/includes/_wpc.md, source/includes/_xmedia.md.erb, source/includes/_xmedia_channel.md.erb
**References**: [EDGE-9874](https://jira.gannett.com/browse/EDGE-9874)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1949
Changes in wpc., xmedia and xmedia channel reports
=> EDGE-9874 Brand Amplifier

source/includes/_wpc.md, source/includes/_xmedia.md.erb, source/includes/_xmedia_channel.md.erb
**References**: [EDGE-9998](https://jira.gannett.com/browse/EDGE-9998)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1956
We needed to add form submissions and priority_page_views totals
=> EDGE-9998 | update_brand_amplifier_api

source/includes/_daily_campaign_activity.md, source/includes/_search_campaign_metrics.md.erb
**References**: [EDGE-10056](https://jira.gannett.com/browse/EDGE-10056)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1966
A new API for daily campaign activities
=> EDGE-10056 | create_daily_campaign_activity_api

source/includes/_daily_campaign_activity.md
**References**: [EDGE-10385](https://jira.gannett.com/browse/EDGE-10385)
**Code PR**: https://github.com/GannettDigital/reach-analytics-reporting-service/pull/1988
We need to add source field to the campaign details in dca report.
=> EDGE-10385 | add_source_to_dca_api
